language:
    c

compiler:
    - gcc
    - clang

before_script:
    - sudo apt-get update
    - sudo apt-get install valgrind

script:
    make && make run_tests

notifications:
  recipients:
    - chutsu@gmail.com
  email:
    on_success: change
    on_failure: always
