site_name: cog
pages:
- Cog: index.md
- Installation: installation.md
- API:
    - darray: api/darray.md
    - hashmap: api/hashmap.md
    - list: api/list.md
    - munit: api/munit.md
    - stack: api/stack.md
    - utils: api/utils.md
- license: license.md

theme: readthedocs
